version: '3.8'

services:
  aliclic-api:
    build: .
    container_name: aliclic-cobertura-api
    restart: always
    environment:
      - TZ=America/Lima
    networks:
      - n8n_default # Usa la misma red que n8n-traefik-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cobertura.rule=Host(`coordenadas.tuimagen-viral.com`)"
      - "traefik.http.routers.cobertura.entrypoints=web" # Cambia a websecure si ya tienes SSL
      - "traefik.http.services.cobertura.loadbalancer.server.port=8000"

networks:
  n8n_default:
    external: true
